/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javapos;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javapos.MyConnection.getConnection;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class AdminHome extends javax.swing.JFrame {

    Object helloAdminButtonasdasdasd;

    /**
     * Creates new form MyHome
     */
    
    public AdminHome() {
        initComponents();
        refreshTableStatus();
        tableStatusRefreshTimer();
       
        
    }
    
    private final int timeLimit=1000;
    
    //.....................START OF TABLE STATUS REFRESH CODE...................
    public void tableStatusRefreshTimer()
    {
        new java.util.Timer().schedule( 
                new java.util.TimerTask() {
                    @Override
                    public void run() {
                        refreshTableStatus();
                    }
                }, 
                 timeLimit
            );
    }
    public void refreshTableStatus()
    {
        
         for(int i=1;i<=12;i++)
         {
             if(tableStatusChecker(i)==1)
             {
                 switch(i)
                 {
                     case 1:TableOneButton.setEnabled(false);break;
                     case 2:TableTwoButton.setEnabled(false);break;
                     case 3:TableThreeButton.setEnabled(false);break;
                     case 4:TableFourButton.setEnabled(false);break;
                     case 5:TableFiveButton.setEnabled(false);break;
                     case 6:TableSixButton.setEnabled(false);break;
                     case 7:TableSevenButton.setEnabled(false);break;
                     case 8:TableEightButton.setEnabled(false);break;
                     case 9:TableNineButton.setEnabled(false);break;
                     case 10:TableTenButton.setEnabled(false);break;
                     case 11:TableElevenButton.setEnabled(false);break;
                     case 12:TableTwelveButton.setEnabled(false);break;
                 }
             }
         }
    }
    public int tableStatusChecker(int tableNo)
    {
        String query="SELECT * FROM reservedtables WHERE tableNO="+tableNo;
        try{
                Statement st = MyConnection.getConnection().createStatement();
                ResultSet rs = st.executeQuery(query);
               if(rs.absolute(1))
               {
                   st.close();
                   rs.close();
                   return 1;
                   
               }
               else
               {
                 st.close();
                 rs.close();
                 return 0;
               }
               
               
           }
           catch(SQLException ex){
                Logger.getLogger(AdminHome.class.getName()).log(Level.SEVERE, null, ex);
           }catch(Exception ex)
           {
               ex.printStackTrace();
            
           }
        return 0;
        
        
    }
    
    
    //..................END OF TABLE STATUS REFRESH................................
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_login_logout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dateLab2 = new javax.swing.JLabel();
        dateLab = new javax.swing.JLabel();
        timeLab = new javax.swing.JLabel();
        btn_go_to_kitchen = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lbl_tb_txt25 = new javax.swing.JLabel();
        lbl_tb_txt26 = new javax.swing.JLabel();
        lbl_tb_txt27 = new javax.swing.JLabel();
        lbl_tb_txt28 = new javax.swing.JLabel();
        lbl_tb_txt29 = new javax.swing.JLabel();
        lbl_tb_txt30 = new javax.swing.JLabel();
        lbl_tb_txt31 = new javax.swing.JLabel();
        lbl_tb_txt32 = new javax.swing.JLabel();
        lbl_tb_txt33 = new javax.swing.JLabel();
        lbl_tb_txt34 = new javax.swing.JLabel();
        lbl_tb_txt35 = new javax.swing.JLabel();
        lbl_tb_txt36 = new javax.swing.JLabel();
        TableOneButton = new javax.swing.JButton();
        TableTwoButton = new javax.swing.JButton();
        TableThreeButton = new javax.swing.JButton();
        TableFourButton = new javax.swing.JButton();
        TableSixButton = new javax.swing.JButton();
        TableSevenButton = new javax.swing.JButton();
        TableEightButton = new javax.swing.JButton();
        TableNineButton = new javax.swing.JButton();
        TableTenButton = new javax.swing.JButton();
        TableElevenButton = new javax.swing.JButton();
        TableTwelveButton = new javax.swing.JButton();
        TableFiveButton = new javax.swing.JButton();
        TableOneButtonCancel = new javax.swing.JButton();
        TableTwoButtonCancel = new javax.swing.JButton();
        TableThreeButtonCancel = new javax.swing.JButton();
        TableFourButtonCancel = new javax.swing.JButton();
        TableFiveButtonCancel = new javax.swing.JButton();
        TableSixButtonCancel = new javax.swing.JButton();
        TableSevenButtonCancel = new javax.swing.JButton();
        TableEightButtonCancel = new javax.swing.JButton();
        TableNineButtonCancel = new javax.swing.JButton();
        TableTenButtonCancel = new javax.swing.JButton();
        TableElevenButtonCancel = new javax.swing.JButton();
        TableTwelveButtonCancel = new javax.swing.JButton();
        btn_settings = new javax.swing.JButton();
        lbl_tb_txt_topic = new javax.swing.JLabel();
        RefreshButtton = new javax.swing.JButton();

        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(7, 198, 168));

        jLabel1.setFont(new java.awt.Font("French Script MT", 1, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Knukles");

        jLabel2.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Resturent");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/images/InterfaceImages/Untitled-1.png"))); // NOI18N

        btn_login_logout.setText("Logout");
        btn_login_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_logoutActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Select a table from the right ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("click button above to start.");

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel6.setText("                  AND");

        dateLab2.setBackground(new java.awt.Color(7, 198, 168));
        dateLab2.setFont(new java.awt.Font("Bauhaus 93", 0, 48)); // NOI18N
        dateLab2.setForeground(new java.awt.Color(255, 255, 255));
        dateLab2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLab2.setOpaque(true);

        dateLab.setBackground(new java.awt.Color(7, 198, 168));
        dateLab.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        dateLab.setForeground(new java.awt.Color(255, 255, 255));
        dateLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLab.setOpaque(true);

        timeLab.setBackground(new java.awt.Color(7, 198, 168));
        timeLab.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        timeLab.setForeground(new java.awt.Color(255, 255, 255));
        timeLab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeLab.setOpaque(true);

        btn_go_to_kitchen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/images/InterfaceImages/kitchen.png"))); // NOI18N
        btn_go_to_kitchen.setText("Go to Kitchen");
        btn_go_to_kitchen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_go_to_kitchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_go_to_kitchenActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("© 2018 Team CODE RIPPERS All Rights Reserved");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(timeLab, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateLab2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLab, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btn_go_to_kitchen, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addComponent(btn_login_logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_login_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(timeLab, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dateLab2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateLab, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(btn_go_to_kitchen, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        lbl_tb_txt25.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt25.setText("Table 1");

        lbl_tb_txt26.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt26.setText("Table 2");

        lbl_tb_txt27.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt27.setText("Table 3");

        lbl_tb_txt28.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt28.setText("Table 4");

        lbl_tb_txt29.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt29.setText("Table 5");

        lbl_tb_txt30.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt30.setText("Table 6");

        lbl_tb_txt31.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt31.setText("Table 7");

        lbl_tb_txt32.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt32.setText("Table 8");

        lbl_tb_txt33.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt33.setText("Table 9");

        lbl_tb_txt34.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt34.setText("Table 10");

        lbl_tb_txt35.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt35.setText("Table 11");

        lbl_tb_txt36.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt36.setText("Table 12");

        TableOneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/images/InterfaceImages/table.png"))); // NOI18N
        TableOneButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TableOneButtonFocusGained(evt);
            }
        });
        TableOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableOneButtonActionPerformed(evt);
            }
        });

        TableTwoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/images/InterfaceImages/table.png"))); // NOI18N
        TableTwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableTwoButtonActionPerformed(evt);
            }
        });

        TableThreeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/images/InterfaceImages/table.png"))); // NOI18N
        TableThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableThreeButtonActionPerformed(evt);
            }
        });

        TableFourButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/images/InterfaceImages/table.png"))); // NOI18N
        TableFourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableFourButtonActionPerformed(evt);
            }
        });

        TableSixButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/images/InterfaceImages/family_table.png"))); // NOI18N
        TableSixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableSixButtonActionPerformed(evt);
            }
        });

        TableSevenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/images/InterfaceImages/family_table.png"))); // NOI18N
        TableSevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableSevenButtonActionPerformed(evt);
            }
        });

        TableEightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/images/InterfaceImages/family_table.png"))); // NOI18N
        TableEightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableEightButtonActionPerformed(evt);
            }
        });

        TableNineButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/images/InterfaceImages/table.png"))); // NOI18N
        TableNineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableNineButtonActionPerformed(evt);
            }
        });

        TableTenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/images/InterfaceImages/table.png"))); // NOI18N
        TableTenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableTenButtonActionPerformed(evt);
            }
        });

        TableElevenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/images/InterfaceImages/table.png"))); // NOI18N
        TableElevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableElevenButtonActionPerformed(evt);
            }
        });

        TableTwelveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/images/InterfaceImages/table.png"))); // NOI18N
        TableTwelveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableTwelveButtonActionPerformed(evt);
            }
        });

        TableFiveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/images/InterfaceImages/family_table.png"))); // NOI18N
        TableFiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableFiveButtonActionPerformed(evt);
            }
        });

        TableOneButtonCancel.setText("X");
        TableOneButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableOneButtonCancelActionPerformed(evt);
            }
        });

        TableTwoButtonCancel.setText("X");
        TableTwoButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableTwoButtonCancelActionPerformed(evt);
            }
        });

        TableThreeButtonCancel.setText("X");
        TableThreeButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableThreeButtonCancelActionPerformed(evt);
            }
        });

        TableFourButtonCancel.setText("X");
        TableFourButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableFourButtonCancelActionPerformed(evt);
            }
        });

        TableFiveButtonCancel.setText("X");
        TableFiveButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableFiveButtonCancelActionPerformed(evt);
            }
        });

        TableSixButtonCancel.setText("X");
        TableSixButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableSixButtonCancelActionPerformed(evt);
            }
        });

        TableSevenButtonCancel.setText("X");
        TableSevenButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableSevenButtonCancelActionPerformed(evt);
            }
        });

        TableEightButtonCancel.setText("X");
        TableEightButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableEightButtonCancelActionPerformed(evt);
            }
        });

        TableNineButtonCancel.setText("X");
        TableNineButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableNineButtonCancelActionPerformed(evt);
            }
        });

        TableTenButtonCancel.setText("X");
        TableTenButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableTenButtonCancelActionPerformed(evt);
            }
        });

        TableElevenButtonCancel.setText("X");
        TableElevenButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableElevenButtonCancelActionPerformed(evt);
            }
        });

        TableTwelveButtonCancel.setText("X");
        TableTwelveButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableTwelveButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(TableSixButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TableSixButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(419, 419, 419))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_tb_txt33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TableNineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(185, 185, 185)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TableTenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_tb_txt34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TableTenButtonCancel)
                                .addGap(131, 131, 131)
                                .addComponent(TableElevenButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TableElevenButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TableEightButton)
                            .addComponent(TableTwelveButton)
                            .addComponent(lbl_tb_txt32, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TableFourButton)
                            .addComponent(lbl_tb_txt28, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_tb_txt30, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_tb_txt25, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addComponent(TableOneButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TableOneButtonCancel)))
                                    .addComponent(TableNineButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TableFiveButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(144, 144, 144)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TableTwoButton)
                                    .addComponent(lbl_tb_txt26, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TableTwoButtonCancel)
                        .addGap(124, 124, 124)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbl_tb_txt31, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(295, 295, 295))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbl_tb_txt27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(TableSevenButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TableSevenButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(TableThreeButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TableThreeButtonCancel)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TableFiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_tb_txt29, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_tb_txt35, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)
                        .addComponent(lbl_tb_txt36, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TableFourButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TableEightButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TableTwelveButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TableTwoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TableThreeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TableFourButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TableOneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TableTwoButtonCancel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TableThreeButtonCancel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TableFourButtonCancel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(TableOneButtonCancel))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_tb_txt26, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_tb_txt25)
                            .addComponent(lbl_tb_txt27))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TableSixButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TableSevenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TableFiveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TableFiveButtonCancel)
                            .addComponent(TableSixButtonCancel)
                            .addComponent(TableSevenButtonCancel)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbl_tb_txt28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TableEightButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TableEightButtonCancel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tb_txt29)
                    .addComponent(lbl_tb_txt31)
                    .addComponent(lbl_tb_txt32)
                    .addComponent(lbl_tb_txt30))
                .addGap(107, 107, 107)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TableNineButton)
                            .addComponent(TableNineButtonCancel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_tb_txt33))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TableTenButton)
                                    .addComponent(TableElevenButton)
                                    .addComponent(TableTwelveButton))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TableTenButtonCancel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TableElevenButtonCancel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TableTwelveButtonCancel, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_tb_txt34)
                                .addComponent(lbl_tb_txt35))
                            .addComponent(lbl_tb_txt36, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        btn_settings.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEWMAL THARINDU\\Documents\\GitHub\\JavaFinalProject\\IndrajithCompleteLoginHere\\images\\settings.png")); // NOI18N
        btn_settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_settingsActionPerformed(evt);
            }
        });

        lbl_tb_txt_topic.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_tb_txt_topic.setText("  Select a table for dining");

        RefreshButtton.setText("REFRESH");
        RefreshButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(RefreshButtton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_settings, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(lbl_tb_txt_topic, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbl_tb_txt_topic, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RefreshButtton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_settings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1834, 1042));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_login_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_logoutActionPerformed
        SignUp signup = new SignUp();
        signup.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_login_logoutActionPerformed

    private void btn_go_to_kitchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_go_to_kitchenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_go_to_kitchenActionPerformed

    private void TableOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableOneButtonActionPerformed

        TableOneButton.setEnabled(false);
        insertReservation(1);

    }//GEN-LAST:event_TableOneButtonActionPerformed

    private void TableTwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableTwoButtonActionPerformed

         TableTwoButton.setEnabled(false);
        insertReservation(2);

    }//GEN-LAST:event_TableTwoButtonActionPerformed

    private void TableThreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableThreeButtonActionPerformed

         TableThreeButton.setEnabled(false);
        insertReservation(31);
    }//GEN-LAST:event_TableThreeButtonActionPerformed

    private void TableFourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableFourButtonActionPerformed
        TableFourButton.setEnabled(false);
        insertReservation(4);

    }//GEN-LAST:event_TableFourButtonActionPerformed

    private void TableSixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableSixButtonActionPerformed

        TableSixButton.setEnabled(false);
        insertReservation(6);

    }//GEN-LAST:event_TableSixButtonActionPerformed

    private void TableSevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableSevenButtonActionPerformed

         TableSevenButton.setEnabled(false);
        insertReservation(7);

    }//GEN-LAST:event_TableSevenButtonActionPerformed

    private void TableEightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableEightButtonActionPerformed
        
         TableEightButton.setEnabled(false);
        insertReservation(8);
    }//GEN-LAST:event_TableEightButtonActionPerformed

    private void TableNineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableNineButtonActionPerformed

         TableNineButton.setEnabled(false);
        insertReservation(9);

    }//GEN-LAST:event_TableNineButtonActionPerformed

    private void TableTenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableTenButtonActionPerformed

       TableTenButton.setEnabled(false);
        insertReservation(10);

    }//GEN-LAST:event_TableTenButtonActionPerformed

    private void TableElevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableElevenButtonActionPerformed

        TableElevenButton.setEnabled(false);
        insertReservation(11);

    }//GEN-LAST:event_TableElevenButtonActionPerformed

    private void TableTwelveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableTwelveButtonActionPerformed

         TableTwelveButton.setEnabled(false);
        insertReservation(12);

    }//GEN-LAST:event_TableTwelveButtonActionPerformed

    private void TableFiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableFiveButtonActionPerformed
        TableFiveButton.setEnabled(false);
        insertReservation(5);

    }//GEN-LAST:event_TableFiveButtonActionPerformed
    public void insertReservation(int tableNo)
    {
           String query="INSERT INTO reservedtables(tableNo) VALUES(?)";
           try{
               PreparedStatement obj = MyConnection.getConnection().prepareStatement(query);
               obj.setInt(1,tableNo);
               
                 if(obj.executeUpdate()>0){
                    //JOptionPane.showMessageDialog(null, "Reserved");
                }
                 obj.close();
           }
           catch(SQLException ex){
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
           }catch(Exception ex)
           {
               ex.printStackTrace();
            
           }
    }
public void  deleteReservation(int tableNo)
    {
    
    String query="DELETE FROM reservedtables WHERE tableNo="+tableNo;
    try
    {
        PreparedStatement obj = MyConnection.getConnection().prepareStatement(query);
        obj.executeUpdate(query);
        obj.close();
    }
    catch(SQLException ex){
        Logger.getLogger(Register.class.getName()).log(Level.SEVERE,null,ex);
    }
    }
    private void btn_settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_settingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_settingsActionPerformed

    private void TableOneButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TableOneButtonFocusGained
                    
    }//GEN-LAST:event_TableOneButtonFocusGained

    private void TableOneButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableOneButtonCancelActionPerformed
           deleteReservation(1);
           TableOneButton.setEnabled(true);
    }//GEN-LAST:event_TableOneButtonCancelActionPerformed

    private void TableTwoButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableTwoButtonCancelActionPerformed
         deleteReservation(2);
         TableTwoButton.setEnabled(true);
    }//GEN-LAST:event_TableTwoButtonCancelActionPerformed

    private void TableThreeButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableThreeButtonCancelActionPerformed
        deleteReservation(3);
         TableThreeButton.setEnabled(true);
    }//GEN-LAST:event_TableThreeButtonCancelActionPerformed

    private void TableFourButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableFourButtonCancelActionPerformed
        deleteReservation(4);
         TableFourButton.setEnabled(true);
    }//GEN-LAST:event_TableFourButtonCancelActionPerformed

    private void TableFiveButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableFiveButtonCancelActionPerformed
       deleteReservation(5);
         TableFiveButton.setEnabled(true);
    }//GEN-LAST:event_TableFiveButtonCancelActionPerformed

    private void TableSixButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableSixButtonCancelActionPerformed
        deleteReservation(6);
         TableSixButton.setEnabled(true);
    }//GEN-LAST:event_TableSixButtonCancelActionPerformed

    private void TableSevenButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableSevenButtonCancelActionPerformed
        deleteReservation(7);
         TableSevenButton.setEnabled(true);
    }//GEN-LAST:event_TableSevenButtonCancelActionPerformed

    private void TableEightButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableEightButtonCancelActionPerformed
        deleteReservation(8);
         TableEightButton.setEnabled(true);
    }//GEN-LAST:event_TableEightButtonCancelActionPerformed

    private void TableNineButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableNineButtonCancelActionPerformed
        deleteReservation(9);
         TableNineButton.setEnabled(true);
    }//GEN-LAST:event_TableNineButtonCancelActionPerformed

    private void TableTenButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableTenButtonCancelActionPerformed
        deleteReservation(10);
         TableTenButton.setEnabled(true);
    }//GEN-LAST:event_TableTenButtonCancelActionPerformed

    private void TableElevenButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableElevenButtonCancelActionPerformed
       deleteReservation(11);
         TableElevenButton.setEnabled(true);
    }//GEN-LAST:event_TableElevenButtonCancelActionPerformed

    private void TableTwelveButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableTwelveButtonCancelActionPerformed
       deleteReservation(12);
         TableTwelveButton.setEnabled(true);
    }//GEN-LAST:event_TableTwelveButtonCancelActionPerformed

    private void RefreshButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButttonActionPerformed
         
        this.dispose();
        new AdminHome().setVisible(true);
         
    }//GEN-LAST:event_RefreshButttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new AdminHome().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RefreshButtton;
    private javax.swing.JButton TableEightButton;
    private javax.swing.JButton TableEightButtonCancel;
    private javax.swing.JButton TableElevenButton;
    private javax.swing.JButton TableElevenButtonCancel;
    private javax.swing.JButton TableFiveButton;
    private javax.swing.JButton TableFiveButtonCancel;
    private javax.swing.JButton TableFourButton;
    private javax.swing.JButton TableFourButtonCancel;
    private javax.swing.JButton TableNineButton;
    private javax.swing.JButton TableNineButtonCancel;
    private javax.swing.JButton TableOneButton;
    private javax.swing.JButton TableOneButtonCancel;
    private javax.swing.JButton TableSevenButton;
    private javax.swing.JButton TableSevenButtonCancel;
    private javax.swing.JButton TableSixButton;
    private javax.swing.JButton TableSixButtonCancel;
    private javax.swing.JButton TableTenButton;
    private javax.swing.JButton TableTenButtonCancel;
    private javax.swing.JButton TableThreeButton;
    private javax.swing.JButton TableThreeButtonCancel;
    private javax.swing.JButton TableTwelveButton;
    private javax.swing.JButton TableTwelveButtonCancel;
    private javax.swing.JButton TableTwoButton;
    private javax.swing.JButton TableTwoButtonCancel;
    private javax.swing.JButton btn_go_to_kitchen;
    private javax.swing.JButton btn_login_logout;
    private javax.swing.JButton btn_settings;
    private javax.swing.JLabel dateLab;
    private javax.swing.JLabel dateLab2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbl_tb_txt25;
    private javax.swing.JLabel lbl_tb_txt26;
    private javax.swing.JLabel lbl_tb_txt27;
    private javax.swing.JLabel lbl_tb_txt28;
    private javax.swing.JLabel lbl_tb_txt29;
    private javax.swing.JLabel lbl_tb_txt30;
    private javax.swing.JLabel lbl_tb_txt31;
    private javax.swing.JLabel lbl_tb_txt32;
    private javax.swing.JLabel lbl_tb_txt33;
    private javax.swing.JLabel lbl_tb_txt34;
    private javax.swing.JLabel lbl_tb_txt35;
    private javax.swing.JLabel lbl_tb_txt36;
    private javax.swing.JLabel lbl_tb_txt_topic;
    private javax.swing.JLabel timeLab;
    // End of variables declaration//GEN-END:variables
}
