/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javapos;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SEWMAL THARINDU
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    private int timeLimit=10000;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl_tb1 = new javax.swing.JLabel();
        lbl_tb2 = new javax.swing.JLabel();
        lbl_tb3 = new javax.swing.JLabel();
        lbl_tb4 = new javax.swing.JLabel();
        lbl_tb5 = new javax.swing.JLabel();
        lbl_tb6 = new javax.swing.JLabel();
        lbl_tb7 = new javax.swing.JLabel();
        lbl_tb8 = new javax.swing.JLabel();
        lbl_tb9 = new javax.swing.JLabel();
        lbl_tb10 = new javax.swing.JLabel();
        lbl_tb11 = new javax.swing.JLabel();
        lbl_tb12 = new javax.swing.JLabel();
        lbl_tb_txt1 = new javax.swing.JLabel();
        lbl_tb_txt2 = new javax.swing.JLabel();
        lbl_tb_txt3 = new javax.swing.JLabel();
        lbl_tb_txt4 = new javax.swing.JLabel();
        lbl_tb_txt5 = new javax.swing.JLabel();
        lbl_tb_txt6 = new javax.swing.JLabel();
        lbl_tb_txt7 = new javax.swing.JLabel();
        lbl_tb_txt8 = new javax.swing.JLabel();
        lbl_tb_txt9 = new javax.swing.JLabel();
        lbl_tb_txt10 = new javax.swing.JLabel();
        lbl_tb_txt11 = new javax.swing.JLabel();
        lbl_tb_txt12 = new javax.swing.JLabel();
        TableFiveButton = new javax.swing.JButton();
        TableFourButton = new javax.swing.JButton();
        TableTwoButton = new javax.swing.JButton();
        TableThreeButton = new javax.swing.JButton();
        TableOneButton = new javax.swing.JButton();
        TableSixButton = new javax.swing.JButton();
        TableSevenButton = new javax.swing.JButton();
        TableEightButton = new javax.swing.JButton();
        TableNineButton = new javax.swing.JButton();
        TableTenButton = new javax.swing.JButton();
        TableElevenButton = new javax.swing.JButton();
        TableTwelveButton = new javax.swing.JButton();
        lbl_tb_txt_topic = new javax.swing.JLabel();
        btn_go_to_kitchen = new javax.swing.JButton();
        btn_settings = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_refresh = new javax.swing.JButton();
        btn_login_logout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_GetTakeaway = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POS System - Home Page");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_tb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb1.setOpaque(true);

        lbl_tb2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb2.setOpaque(true);

        lbl_tb3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb3.setOpaque(true);

        lbl_tb4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb4.setOpaque(true);

        lbl_tb5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb5.setOpaque(true);

        lbl_tb6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb6.setOpaque(true);

        lbl_tb7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb7.setOpaque(true);

        lbl_tb8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb8.setOpaque(true);

        lbl_tb9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb9.setOpaque(true);

        lbl_tb10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb10.setOpaque(true);

        lbl_tb11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb11.setOpaque(true);

        lbl_tb12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb12.setOpaque(true);

        lbl_tb_txt1.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt1.setText("Table 1");
        lbl_tb_txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_tb_txt1MouseClicked(evt);
            }
        });

        lbl_tb_txt2.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt2.setText("Table 2");

        lbl_tb_txt3.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt3.setText("Table 3");

        lbl_tb_txt4.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt4.setText("Table 4");

        lbl_tb_txt5.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt5.setText("Table 5");

        lbl_tb_txt6.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt6.setText("Table 6");

        lbl_tb_txt7.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt7.setText("Table 7");

        lbl_tb_txt8.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt8.setText("Table 8");

        lbl_tb_txt9.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt9.setText("Table 9");

        lbl_tb_txt10.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt10.setText("Table 10");

        lbl_tb_txt11.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt11.setText("Table 11");

        lbl_tb_txt12.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt12.setText("Table 12");

        TableFiveButton.setIcon(new javax.swing.ImageIcon("/home/airoshan/NetBeansProjects/-Java-PointOfSales-System-for-Resturent-master/IndrajithCompleteLoginHere/images/family_table.png")); // NOI18N
        TableFiveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableFiveButtonMouseClicked(evt);
            }
        });

        TableFourButton.setIcon(new javax.swing.ImageIcon("/home/airoshan/NetBeansProjects/-Java-PointOfSales-System-for-Resturent-master/IndrajithCompleteLoginHere/images/table.png")); // NOI18N
        TableFourButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableFourButtonMouseClicked(evt);
            }
        });

        TableTwoButton.setIcon(new javax.swing.ImageIcon("/home/airoshan/NetBeansProjects/-Java-PointOfSales-System-for-Resturent-master/IndrajithCompleteLoginHere/images/table.png")); // NOI18N
        TableTwoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableTwoButtonMouseClicked(evt);
            }
        });

        TableThreeButton.setIcon(new javax.swing.ImageIcon("/home/airoshan/NetBeansProjects/-Java-PointOfSales-System-for-Resturent-master/IndrajithCompleteLoginHere/images/table.png")); // NOI18N
        TableThreeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableThreeButtonMouseClicked(evt);
            }
        });

        TableOneButton.setIcon(new javax.swing.ImageIcon("/home/airoshan/NetBeansProjects/-Java-PointOfSales-System-for-Resturent-master/IndrajithCompleteLoginHere/images/table.png")); // NOI18N
        TableOneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableOneButtonMouseClicked(evt);
            }
        });
        TableOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableOneButtonActionPerformed(evt);
            }
        });

        TableSixButton.setIcon(new javax.swing.ImageIcon("/home/airoshan/NetBeansProjects/-Java-PointOfSales-System-for-Resturent-master/IndrajithCompleteLoginHere/images/family_table.png")); // NOI18N
        TableSixButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSixButtonMouseClicked(evt);
            }
        });

        TableSevenButton.setIcon(new javax.swing.ImageIcon("/home/airoshan/NetBeansProjects/-Java-PointOfSales-System-for-Resturent-master/IndrajithCompleteLoginHere/images/family_table.png")); // NOI18N
        TableSevenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSevenButtonMouseClicked(evt);
            }
        });

        TableEightButton.setIcon(new javax.swing.ImageIcon("/home/airoshan/NetBeansProjects/-Java-PointOfSales-System-for-Resturent-master/IndrajithCompleteLoginHere/images/family_table.png")); // NOI18N
        TableEightButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableEightButtonMouseClicked(evt);
            }
        });

        TableNineButton.setIcon(new javax.swing.ImageIcon("/home/airoshan/NetBeansProjects/-Java-PointOfSales-System-for-Resturent-master/IndrajithCompleteLoginHere/images/table.png")); // NOI18N
        TableNineButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableNineButtonMouseClicked(evt);
            }
        });

        TableTenButton.setIcon(new javax.swing.ImageIcon("/home/airoshan/NetBeansProjects/-Java-PointOfSales-System-for-Resturent-master/IndrajithCompleteLoginHere/images/table.png")); // NOI18N
        TableTenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableTenButtonMouseClicked(evt);
            }
        });

        TableElevenButton.setIcon(new javax.swing.ImageIcon("/home/airoshan/NetBeansProjects/-Java-PointOfSales-System-for-Resturent-master/IndrajithCompleteLoginHere/images/table.png")); // NOI18N
        TableElevenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableElevenButtonMouseClicked(evt);
            }
        });

        TableTwelveButton.setIcon(new javax.swing.ImageIcon("/home/airoshan/NetBeansProjects/-Java-PointOfSales-System-for-Resturent-master/IndrajithCompleteLoginHere/images/table.png")); // NOI18N
        TableTwelveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableTwelveButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(lbl_tb_txt11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_tb8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_tb4)
                            .addComponent(lbl_tb12)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_tb1)
                                    .addComponent(lbl_tb5)
                                    .addComponent(lbl_tb9))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(109, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_tb2)
                                        .addGap(93, 93, 93)
                                        .addComponent(lbl_tb3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TableOneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(lbl_tb_txt1))
                                            .addComponent(TableFiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(lbl_tb_txt5))
                                            .addComponent(TableNineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(lbl_tb_txt9)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(lbl_tb_txt6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lbl_tb_txt7)
                                                        .addGap(80, 80, 80))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(lbl_tb_txt2)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lbl_tb_txt3)
                                                        .addGap(79, 79, 79))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(lbl_tb7)
                                                        .addGap(94, 94, 94))
                                                    .addComponent(lbl_tb11, javax.swing.GroupLayout.Alignment.TRAILING)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TableTwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TableSixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TableTenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(12, 12, 12)
                                                        .addComponent(lbl_tb_txt10)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TableSevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TableThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TableElevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(66, 66, 66)))))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(TableFourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(87, 87, 87))
                                    .addComponent(TableEightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TableTwelveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_tb_txt12)
                                            .addComponent(lbl_tb_txt8)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_tb_txt4)
                                .addGap(100, 100, 100)))))
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tb10)
                    .addComponent(lbl_tb6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_tb4)
                    .addComponent(lbl_tb1)
                    .addComponent(lbl_tb2)
                    .addComponent(lbl_tb3))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TableFourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TableThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TableOneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TableTwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tb_txt1)
                    .addComponent(lbl_tb_txt3)
                    .addComponent(lbl_tb_txt4)
                    .addComponent(lbl_tb_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tb5)
                    .addComponent(lbl_tb6)
                    .addComponent(lbl_tb7)
                    .addComponent(lbl_tb8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TableEightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TableSixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TableSevenButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TableFiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tb_txt5)
                    .addComponent(lbl_tb_txt7)
                    .addComponent(lbl_tb_txt8)
                    .addComponent(lbl_tb_txt6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TableNineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_tb10)
                                .addComponent(lbl_tb9)
                                .addComponent(lbl_tb11)
                                .addComponent(lbl_tb12))
                            .addComponent(TableTenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TableElevenButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TableTwelveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tb_txt10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_tb_txt11)
                        .addComponent(lbl_tb_txt12))
                    .addComponent(lbl_tb_txt9))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        lbl_tb_txt_topic.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_tb_txt_topic.setText("Select a table for dining");

        btn_go_to_kitchen.setText("Go to Kitchen");
        btn_go_to_kitchen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_go_to_kitchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_go_to_kitchenActionPerformed(evt);
            }
        });

        btn_settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_settingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_go_to_kitchen)
                .addGap(613, 613, 613)
                .addComponent(btn_settings, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_tb_txt_topic)
                .addGap(296, 296, 296))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_tb_txt_topic)
                        .addGap(652, 652, 652))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_go_to_kitchen)
                    .addComponent(btn_settings))
                .addGap(24, 24, 24))
        );

        jPanel2.setBackground(new java.awt.Color(7, 198, 168));

        jLabel1.setFont(new java.awt.Font("French Script MT", 1, 48)); // NOI18N
        jLabel1.setText("Knukles");

        jLabel2.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel2.setText("Resturent");

        btn_refresh.setText("Refresh");

        btn_login_logout.setText("Login");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Information :-");

        btn_GetTakeaway.setText("Get takeaway");
        btn_GetTakeaway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GetTakeawayActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 102));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(3);
        jTextArea1.setText("Select a table from the right\nor click \"Get take away\" \nbutton bolow to start.");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btn_refresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_login_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(159, 159, 159)
                            .addComponent(jLabel4)
                            .addGap(26, 26, 26)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(202, 202, 202)
                            .addComponent(btn_GetTakeaway, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(80, 80, 80))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)))))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_login_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btn_GetTakeaway, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_go_to_kitchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_go_to_kitchenActionPerformed
        // TODwwweO add your handling code here:wew
    }//GEN-LAST:event_btn_go_to_kitchenActionPerformed

    private void btn_settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_settingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_settingsActionPerformed

    private void btn_GetTakeawayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GetTakeawayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_GetTakeawayActionPerformed

    private void lbl_tb_txt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_tb_txt1MouseClicked
                
    }//GEN-LAST:event_lbl_tb_txt1MouseClicked

    private void TableFiveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableFiveButtonMouseClicked
           
    int confirmed = JOptionPane.showConfirmDialog(null, 
     "Are you sure you want to reserve this table? You won't be able to unreserve it once you reserve", "Exit Program Message Box",
      JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      TableFiveButton.setEnabled(false);
      insertReservation(5);
      
      new java.util.Timer().schedule( 
                new java.util.TimerTask() {
                    @Override
                    public void run() {
                        TableFiveButton.setEnabled(true);
                         deleteReservation(5);
                    }
                }, 
                timeLimit
            );
    }
    else if(confirmed == JOptionPane.NO_OPTION)
    {
        TableFiveButton.setEnabled(true);
    }
        
           
           
    }//GEN-LAST:event_TableFiveButtonMouseClicked

    private void TableOneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableOneButtonMouseClicked
        
     int confirmed = JOptionPane.showConfirmDialog(null, 
     "Are you sure you want to reserve this table? You won't be able to unreserve it once you reserve", "Exit Program Message Box",
      JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      TableOneButton.setEnabled(false);
      insertReservation(1);
      
      new java.util.Timer().schedule( 
                new java.util.TimerTask() {
                    @Override
                    public void run() {
                        TableOneButton.setEnabled(true);
                         deleteReservation(1);
                    }
                }, 
                 timeLimit
            );
    }
    else if(confirmed == JOptionPane.NO_OPTION)
    {
        TableOneButton.setEnabled(true);
    }
        
     
      
        
    }//GEN-LAST:event_TableOneButtonMouseClicked

    private void TableSixButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSixButtonMouseClicked
            int confirmed = JOptionPane.showConfirmDialog(null, 
     "Are you sure you want to reserve this table? You won't be able to unreserve it once you reserve", "Exit Program Message Box",
      JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      TableSixButton.setEnabled(false);
      insertReservation(6);
      
      new java.util.Timer().schedule( 
                new java.util.TimerTask() {
                    @Override
                    public void run() {
                        TableSixButton.setEnabled(true);
                         deleteReservation(6);
                    }
                }, 
                 timeLimit
            );
    }
    else if(confirmed == JOptionPane.NO_OPTION)
    {
        TableSixButton.setEnabled(true);
    }
        
      
    }//GEN-LAST:event_TableSixButtonMouseClicked

    private void TableSevenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSevenButtonMouseClicked
            int confirmed = JOptionPane.showConfirmDialog(null, 
     "Are you sure you want to reserve this table? You won't be able to unreserve it once you reserve", "Exit Program Message Box",
      JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      TableSevenButton.setEnabled(false);
      insertReservation(7);
      
      new java.util.Timer().schedule( 
                new java.util.TimerTask() {
                    @Override
                    public void run() {
                        TableSevenButton.setEnabled(true);
                         deleteReservation(7);
                    }
                }, 
                timeLimit
            );
        
    }
    else if(confirmed == JOptionPane.NO_OPTION)
    {
        TableSevenButton.setEnabled(true);
    }
        
    }//GEN-LAST:event_TableSevenButtonMouseClicked

    private void TableEightButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableEightButtonMouseClicked
            int confirmed = JOptionPane.showConfirmDialog(null, 
     "Are you sure you want to reserve this table? You won't be able to unreserve it once you reserve", "Exit Program Message Box",
      JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      TableEightButton.setEnabled(false);
      insertReservation(8);
      
      new java.util.Timer().schedule( 
                new java.util.TimerTask() {
                    @Override
                    public void run() {
                        TableEightButton.setEnabled(true);
                         deleteReservation(8);
                    }
                }, 
                 timeLimit
            );
    }
    else if(confirmed == JOptionPane.NO_OPTION)
    {
        TableEightButton.setEnabled(true);
    }
        
     
    }//GEN-LAST:event_TableEightButtonMouseClicked

    private void TableNineButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableNineButtonMouseClicked
            int confirmed = JOptionPane.showConfirmDialog(null, 
     "Are you sure you want to reserve this table? You won't be able to unreserve it once you reserve", "Exit Program Message Box",
      JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      TableNineButton.setEnabled(false);
      insertReservation(9);
      
      new java.util.Timer().schedule( 
                new java.util.TimerTask() {
                    @Override
                    public void run() {
                        TableNineButton.setEnabled(true);
                         deleteReservation(9);
                    }
                }, 
                timeLimit
            );
    }
    else if(confirmed == JOptionPane.NO_OPTION)
    {
        TableNineButton.setEnabled(true);
    }
        
       
    }//GEN-LAST:event_TableNineButtonMouseClicked

    private void TableTenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableTenButtonMouseClicked
            int confirmed = JOptionPane.showConfirmDialog(null, 
     "Are you sure you want to reserve this table? You won't be able to unreserve it once you reserve", "Exit Program Message Box",
      JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      TableTenButton.setEnabled(false);
      insertReservation(10);
      
      new java.util.Timer().schedule( 
                new java.util.TimerTask() {
                    @Override
                    public void run() {
                        TableTenButton.setEnabled(true);
                        deleteReservation(10);
                    }
                }, 
                timeLimit
            );
    }
    else if(confirmed == JOptionPane.NO_OPTION)
    {
        TableTenButton.setEnabled(true);
    }
        
       
    }//GEN-LAST:event_TableTenButtonMouseClicked

    private void TableElevenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableElevenButtonMouseClicked
            int confirmed = JOptionPane.showConfirmDialog(null, 
     "Are you sure you want to reserve this table? You won't be able to unreserve it once you reserve", "Exit Program Message Box",
      JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      TableElevenButton.setEnabled(false);
      insertReservation(11);
      new java.util.Timer().schedule( 
                new java.util.TimerTask() {
                    @Override
                    public void run() {
                        TableElevenButton.setEnabled(true);
                         deleteReservation(11);
                    }
                }, 
                 timeLimit
            );
    }
    else if(confirmed == JOptionPane.NO_OPTION)
    {
        TableElevenButton.setEnabled(true);
    }
        
        
    }//GEN-LAST:event_TableElevenButtonMouseClicked

    private void TableTwelveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableTwelveButtonMouseClicked
    int confirmed = JOptionPane.showConfirmDialog(null, 
     "Are you sure you want to reserve this table? You won't be able to unreserve it once you reserve", "Exit Program Message Box",
      JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      TableTwelveButton.setEnabled(false);
      insertReservation(12);
      
      new java.util.Timer().schedule( 
                new java.util.TimerTask() {
                    @Override
                    public void run() {
                        TableTwelveButton.setEnabled(true);
                         deleteReservation(12);
                    }
                }, 
                 timeLimit
            );
    }
    else if(confirmed == JOptionPane.NO_OPTION)
    {
        TableTwelveButton.setEnabled(true);
    }        
    
       
    }//GEN-LAST:event_TableTwelveButtonMouseClicked

    private void TableOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableOneButtonActionPerformed
        
    }//GEN-LAST:event_TableOneButtonActionPerformed

    private void TableTwoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableTwoButtonMouseClicked
     int confirmed = JOptionPane.showConfirmDialog(null, 
     "Are you sure you want to reserve this table? You won't be able to unreserve it once you reserve", "Exit Program Message Box",
      JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      TableTwoButton.setEnabled(false);
      insertReservation(2);
      
      new java.util.Timer().schedule( 
                new java.util.TimerTask() {
                    @Override
                    public void run() {
                        TableTwoButton.setEnabled(true);
                         deleteReservation(2);
                    }
                }, 
                timeLimit
            );// TODO add your handling code here:
    }
    else if(confirmed == JOptionPane.NO_OPTION)
    {
        TableTwoButton.setEnabled(true);
    }
        
        
    }//GEN-LAST:event_TableTwoButtonMouseClicked

    private void TableThreeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableThreeButtonMouseClicked
     int confirmed = JOptionPane.showConfirmDialog(null, 
     "Are you sure you want to reserve this table? You won't be able to unreserve it once you reserve", "Exit Program Message Box",
      JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      TableThreeButton.setEnabled(false);
      insertReservation(3);
      
      new java.util.Timer().schedule( 
                new java.util.TimerTask() {
                    @Override
                    public void run() {
                        TableThreeButton.setEnabled(true);
                         deleteReservation(3);
                    }
                }, 
                timeLimit
            );// TODO add your handling code here:
    }
    else if(confirmed == JOptionPane.NO_OPTION)
    {
        TableThreeButton.setEnabled(true);
    }
        
        
    }//GEN-LAST:event_TableThreeButtonMouseClicked

    private void TableFourButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableFourButtonMouseClicked
               int confirmed = JOptionPane.showConfirmDialog(null, 
     "Are you sure you want to reserve this table? You won't be able to unreserve it once you reserve", "Exit Program Message Box",
      JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      TableFourButton.setEnabled(false);
      insertReservation(4);
      
      new java.util.Timer().schedule( 
                        new java.util.TimerTask() {
                            @Override
                            public void run() {
                                TableFourButton.setEnabled(true);
                                 deleteReservation(4);
                            }
                        }, 
                         timeLimit
                    );// TODO add your handling code here:
    }
    else if(confirmed == JOptionPane.NO_OPTION)
    {
        TableFourButton.setEnabled(true);
    }
        
       
    }//GEN-LAST:event_TableFourButtonMouseClicked
public void insertReservation(int tableNo)
{
           String query="INSERT INTO reservedtables(tableNo) VALUES(?)";
           try{
               PreparedStatement obj = MyConnection.getConnection().prepareStatement(query);
               obj.setInt(1,tableNo);
               
                 if(obj.executeUpdate()>0){
                    //JOptionPane.showMessageDialog(null, "Reserved");
                }
           }
           catch(SQLException ex){
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
           }catch(Exception ex)
           {
               ex.printStackTrace();
            
           }
}
public void  deleteReservation(int tableNo)
{
    
    String query="DELETE FROM reservedtables WHERE tableNo="+tableNo;
    try
    {
        PreparedStatement obj = MyConnection.getConnection().prepareStatement(query);
        obj.executeUpdate(query);
    }
    catch(SQLException ex){
        Logger.getLogger(Register.class.getName()).log(Level.SEVERE,null,ex);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TableEightButton;
    private javax.swing.JButton TableElevenButton;
    private javax.swing.JButton TableFiveButton;
    private javax.swing.JButton TableFourButton;
    private javax.swing.JButton TableNineButton;
    private javax.swing.JButton TableOneButton;
    private javax.swing.JButton TableSevenButton;
    private javax.swing.JButton TableSixButton;
    private javax.swing.JButton TableTenButton;
    private javax.swing.JButton TableThreeButton;
    private javax.swing.JButton TableTwelveButton;
    private javax.swing.JButton TableTwoButton;
    private javax.swing.JButton btn_GetTakeaway;
    private javax.swing.JButton btn_go_to_kitchen;
    private javax.swing.JButton btn_login_logout;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_settings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_tb1;
    private javax.swing.JLabel lbl_tb10;
    private javax.swing.JLabel lbl_tb11;
    private javax.swing.JLabel lbl_tb12;
    private javax.swing.JLabel lbl_tb2;
    private javax.swing.JLabel lbl_tb3;
    private javax.swing.JLabel lbl_tb4;
    private javax.swing.JLabel lbl_tb5;
    private javax.swing.JLabel lbl_tb6;
    private javax.swing.JLabel lbl_tb7;
    private javax.swing.JLabel lbl_tb8;
    private javax.swing.JLabel lbl_tb9;
    private javax.swing.JLabel lbl_tb_txt1;
    private javax.swing.JLabel lbl_tb_txt10;
    private javax.swing.JLabel lbl_tb_txt11;
    private javax.swing.JLabel lbl_tb_txt12;
    private javax.swing.JLabel lbl_tb_txt2;
    private javax.swing.JLabel lbl_tb_txt3;
    private javax.swing.JLabel lbl_tb_txt4;
    private javax.swing.JLabel lbl_tb_txt5;
    private javax.swing.JLabel lbl_tb_txt6;
    private javax.swing.JLabel lbl_tb_txt7;
    private javax.swing.JLabel lbl_tb_txt8;
    private javax.swing.JLabel lbl_tb_txt9;
    private javax.swing.JLabel lbl_tb_txt_topic;
    // End of variables declaration//GEN-END:variables
}
