/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javapos;

/**
 *
 * @author SEWMAL THARINDU
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl_tb1 = new javax.swing.JLabel();
        lbl_tb2 = new javax.swing.JLabel();
        lbl_tb3 = new javax.swing.JLabel();
        lbl_tb4 = new javax.swing.JLabel();
        lbl_tb5 = new javax.swing.JLabel();
        lbl_tb6 = new javax.swing.JLabel();
        lbl_tb7 = new javax.swing.JLabel();
        lbl_tb8 = new javax.swing.JLabel();
        lbl_tb9 = new javax.swing.JLabel();
        lbl_tb10 = new javax.swing.JLabel();
        lbl_tb11 = new javax.swing.JLabel();
        lbl_tb12 = new javax.swing.JLabel();
        lbl_tb_txt1 = new javax.swing.JLabel();
        lbl_tb_txt2 = new javax.swing.JLabel();
        lbl_tb_txt3 = new javax.swing.JLabel();
        lbl_tb_txt4 = new javax.swing.JLabel();
        lbl_tb_txt5 = new javax.swing.JLabel();
        lbl_tb_txt6 = new javax.swing.JLabel();
        lbl_tb_txt7 = new javax.swing.JLabel();
        lbl_tb_txt8 = new javax.swing.JLabel();
        lbl_tb_txt9 = new javax.swing.JLabel();
        lbl_tb_txt10 = new javax.swing.JLabel();
        lbl_tb_txt11 = new javax.swing.JLabel();
        lbl_tb_txt12 = new javax.swing.JLabel();
        lbl_tb_txt_topic = new javax.swing.JLabel();
        btn_go_to_kitchen = new javax.swing.JButton();
        btn_settings = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_refresh = new javax.swing.JButton();
        btn_login_logout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_GetTakeaway = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POS System - Home Page");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_tb1.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEWMAL THARINDU\\Documents\\GitHub\\JavaFinalProject\\IndrajithCompleteLoginHere\\images\\table.png")); // NOI18N
        lbl_tb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb1.setOpaque(true);

        lbl_tb2.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEWMAL THARINDU\\Documents\\GitHub\\JavaFinalProject\\IndrajithCompleteLoginHere\\images\\table.png")); // NOI18N
        lbl_tb2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb2.setOpaque(true);

        lbl_tb3.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEWMAL THARINDU\\Documents\\GitHub\\JavaFinalProject\\IndrajithCompleteLoginHere\\images\\table.png")); // NOI18N
        lbl_tb3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb3.setOpaque(true);

        lbl_tb4.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEWMAL THARINDU\\Documents\\GitHub\\JavaFinalProject\\IndrajithCompleteLoginHere\\images\\table.png")); // NOI18N
        lbl_tb4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb4.setOpaque(true);

        lbl_tb5.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEWMAL THARINDU\\Documents\\GitHub\\JavaFinalProject\\IndrajithCompleteLoginHere\\images\\family_table.png")); // NOI18N
        lbl_tb5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb5.setOpaque(true);

        lbl_tb6.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEWMAL THARINDU\\Documents\\GitHub\\JavaFinalProject\\IndrajithCompleteLoginHere\\images\\family_table.png")); // NOI18N
        lbl_tb6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb6.setOpaque(true);

        lbl_tb7.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEWMAL THARINDU\\Documents\\GitHub\\JavaFinalProject\\IndrajithCompleteLoginHere\\images\\family_table.png")); // NOI18N
        lbl_tb7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb7.setOpaque(true);

        lbl_tb8.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEWMAL THARINDU\\Documents\\GitHub\\JavaFinalProject\\IndrajithCompleteLoginHere\\images\\family_table.png")); // NOI18N
        lbl_tb8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb8.setOpaque(true);

        lbl_tb9.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEWMAL THARINDU\\Documents\\GitHub\\JavaFinalProject\\IndrajithCompleteLoginHere\\images\\table.png")); // NOI18N
        lbl_tb9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb9.setOpaque(true);

        lbl_tb10.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEWMAL THARINDU\\Documents\\GitHub\\JavaFinalProject\\IndrajithCompleteLoginHere\\images\\table.png")); // NOI18N
        lbl_tb10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb10.setOpaque(true);

        lbl_tb11.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEWMAL THARINDU\\Documents\\GitHub\\JavaFinalProject\\IndrajithCompleteLoginHere\\images\\table.png")); // NOI18N
        lbl_tb11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb11.setOpaque(true);

        lbl_tb12.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEWMAL THARINDU\\Documents\\GitHub\\JavaFinalProject\\IndrajithCompleteLoginHere\\images\\table.png")); // NOI18N
        lbl_tb12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tb12.setOpaque(true);

        lbl_tb_txt1.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt1.setText("Table 1");

        lbl_tb_txt2.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt2.setText("Table 2");

        lbl_tb_txt3.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt3.setText("Table 3");

        lbl_tb_txt4.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt4.setText("Table 4");

        lbl_tb_txt5.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt5.setText("Table 5");

        lbl_tb_txt6.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt6.setText("Table 6");

        lbl_tb_txt7.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt7.setText("Table 7");

        lbl_tb_txt8.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt8.setText("Table 8");

        lbl_tb_txt9.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt9.setText("Table 9");

        lbl_tb_txt10.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt10.setText("Table 10");

        lbl_tb_txt11.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt11.setText("Table 11");

        lbl_tb_txt12.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tb_txt12.setText("Table 12");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lbl_tb_txt1)
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 21, Short.MAX_VALUE)
                                .addComponent(lbl_tb_txt2)
                                .addGap(128, 128, 128)
                                .addComponent(lbl_tb_txt3)
                                .addGap(134, 134, 134)
                                .addComponent(lbl_tb_txt4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_tb7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_tb2)
                                        .addGap(93, 93, 93)
                                        .addComponent(lbl_tb3))
                                    .addComponent(lbl_tb11))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lbl_tb_txt5)
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lbl_tb_txt6)
                                .addGap(129, 129, 129)
                                .addComponent(lbl_tb_txt7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_tb_txt8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_tb10)
                                    .addComponent(lbl_tb6))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_tb1)
                            .addComponent(lbl_tb5)
                            .addComponent(lbl_tb9)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lbl_tb_txt9)
                        .addGap(137, 137, 137)
                        .addComponent(lbl_tb_txt10)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_tb4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(lbl_tb_txt11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_tb8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_tb_txt12)
                                .addGap(12, 12, 12))
                            .addComponent(lbl_tb12, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_tb4)
                    .addComponent(lbl_tb1)
                    .addComponent(lbl_tb2)
                    .addComponent(lbl_tb3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tb_txt1)
                    .addComponent(lbl_tb_txt3)
                    .addComponent(lbl_tb_txt4)
                    .addComponent(lbl_tb_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tb5)
                    .addComponent(lbl_tb6)
                    .addComponent(lbl_tb7)
                    .addComponent(lbl_tb8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tb_txt5)
                    .addComponent(lbl_tb_txt6)
                    .addComponent(lbl_tb_txt7)
                    .addComponent(lbl_tb_txt8))
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_tb10)
                    .addComponent(lbl_tb9)
                    .addComponent(lbl_tb11)
                    .addComponent(lbl_tb12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tb_txt9)
                    .addComponent(lbl_tb_txt10)
                    .addComponent(lbl_tb_txt11)
                    .addComponent(lbl_tb_txt12))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        lbl_tb_txt_topic.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_tb_txt_topic.setText("Select a table for dining");

        btn_go_to_kitchen.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEWMAL THARINDU\\Documents\\GitHub\\JavaFinalProject\\IndrajithCompleteLoginHere\\images\\kitchen.png")); // NOI18N
        btn_go_to_kitchen.setText("Go to Kitchen");
        btn_go_to_kitchen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_go_to_kitchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_go_to_kitchenActionPerformed(evt);
            }
        });

        btn_settings.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEWMAL THARINDU\\Documents\\GitHub\\JavaFinalProject\\IndrajithCompleteLoginHere\\images\\settings.png")); // NOI18N
        btn_settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_settingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_tb_txt_topic)
                        .addGap(296, 296, 296))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btn_go_to_kitchen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_settings, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_tb_txt_topic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_go_to_kitchen)
                    .addComponent(btn_settings))
                .addGap(24, 24, 24))
        );

        jPanel2.setBackground(new java.awt.Color(7, 198, 168));

        jLabel1.setFont(new java.awt.Font("French Script MT", 1, 48)); // NOI18N
        jLabel1.setText("Knukles");

        jLabel2.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel2.setText("Resturent");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEWMAL THARINDU\\Documents\\GitHub\\JavaFinalProject\\IndrajithCompleteLoginHere\\images\\Untitled-1.png")); // NOI18N

        btn_refresh.setText("Refresh");

        btn_login_logout.setText("Login");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Information :-");

        btn_GetTakeaway.setText("Get takeaway");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 102));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(3);
        jTextArea1.setText("Select a table from the right\nor click \"Get take away\" \nbutton bolow to start.");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btn_refresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_login_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(159, 159, 159)
                            .addComponent(jLabel4)
                            .addGap(26, 26, 26)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(202, 202, 202)
                            .addComponent(btn_GetTakeaway, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(80, 80, 80))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)))))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_login_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btn_GetTakeaway, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_go_to_kitchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_go_to_kitchenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_go_to_kitchenActionPerformed

    private void btn_settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_settingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_settingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GetTakeaway;
    private javax.swing.JButton btn_go_to_kitchen;
    private javax.swing.JButton btn_login_logout;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_settings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_tb1;
    private javax.swing.JLabel lbl_tb10;
    private javax.swing.JLabel lbl_tb11;
    private javax.swing.JLabel lbl_tb12;
    private javax.swing.JLabel lbl_tb2;
    private javax.swing.JLabel lbl_tb3;
    private javax.swing.JLabel lbl_tb4;
    private javax.swing.JLabel lbl_tb5;
    private javax.swing.JLabel lbl_tb6;
    private javax.swing.JLabel lbl_tb7;
    private javax.swing.JLabel lbl_tb8;
    private javax.swing.JLabel lbl_tb9;
    private javax.swing.JLabel lbl_tb_txt1;
    private javax.swing.JLabel lbl_tb_txt10;
    private javax.swing.JLabel lbl_tb_txt11;
    private javax.swing.JLabel lbl_tb_txt12;
    private javax.swing.JLabel lbl_tb_txt2;
    private javax.swing.JLabel lbl_tb_txt3;
    private javax.swing.JLabel lbl_tb_txt4;
    private javax.swing.JLabel lbl_tb_txt5;
    private javax.swing.JLabel lbl_tb_txt6;
    private javax.swing.JLabel lbl_tb_txt7;
    private javax.swing.JLabel lbl_tb_txt8;
    private javax.swing.JLabel lbl_tb_txt9;
    private javax.swing.JLabel lbl_tb_txt_topic;
    // End of variables declaration//GEN-END:variables
}
